### ISSUE TITLE
Azure: Add option for user to add encrypted volume

### ISSUE THREAD

**Issue by vibhorkumar123** [EnterpriseDB/postgres-deployment#36]
Allow users to choose encrypted volume in Azure

**Comment by dougortiz** [comment]
Volumes have been added and tested on single cluster.

Encryption is still to be added.

**Comment by dougortiz** [comment]
- Volumes have been added to cli as parameters along with type of disks.
- Encryption of disks is still in beta and does not work in Azure.
- Tested on Single Cluster successfully.
- Due to restrictions of Azure Cloud Account unable to test in Multi-Node Cluster Setup

**Pending to re-test Multi-Node Cluster when Azure Cloud account restrictions are updated.**

**Comment by dougortiz** [comment]
Currently in Beta for Terraform Provider.
**This capability will not be available**

**Comment by vibhorkumar123** [comment]
We have redesigned the CLI, which has encrypted volume capabilities.
