### ISSUE TITLE
Replace bash CLI with Golang CLI

### ISSUE THREAD

**Issue by vibhorkumar123** [EnterpriseDB/postgres-deployment#56]
Replace bash CLI with GoLang and design the coding style

**Comment by dougortiz** [comment]
EDB-CLI-GO only supports AWS at this point in time.

Tested successful AWS:
- EPAS - 12 - Single Node Cluster: CentOS8 and RHEL8
- EPAS - 12 - Multi-Node Cluster: CentOS8 and RHEL8
- PG - 12 - Single Node Cluster: CentOS8 and RHEL8
- PG - 12 - Multi-Node Cluster: CentOS8 and RHEL8

**Comment by dougortiz** [comment]
Re-factoring to enable support for AWS, Azure and GCloud

**Comment by dougortiz** [comment]
Regression tested successfully:
- Single Node Cluster EPAS: CentOS8 and RHEL8
- Multi-Node Cluster EPAS: CentOS8 and RHEL8

**Comment by dougortiz** [comment]
Tested successfully - AWS:
- Single Node Cluster EPAS: CentOS7, CentOS8 and RHEL7
- Multi-Node Cluster EPAS: CentOS7, CentOS8 and RHEL7
 
Regression tested successfully:
- Single Node Cluster EPAS: CentOS8 and RHEL8
- Multi-Node Cluster EPAS: CentOS8 and RHEL8

Tested successfully - Azure:
- Single Node Cluster EPAS: CentOS7, CentOS8 and RHEL7
- Multi-Node Cluster EPAS: CentOS7, CentOS8 and RHEL7
- Fails because of bug: EPAS - RHEL8: Single and Multi-Node Cluster

Tested successfully - GCP:
- Single Node Cluster - EPAS: CentOS7, CentOS8, RHEL7 and RHEL8
- Multi-Node Cluster - EPAS: CentOS7, CentOS8, RHEL7 and RHEL8

**Comment by vibhorkumar123** [comment]
GoLang work has been postponed for a while and we have a new interface using python.
